
// Objective-C API for talking to the following Go packages
//
//	tinygo/mpccore
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libmpccore_FRAMEWORK_H__
#define __Libmpccore_FRAMEWORK_H__

#include "Mpccore.objc.h"
#include "Universe.objc.h"

#endif
