// Objective-C API for talking to tinygo/mpccore Go package.
//   gobind -lang=objc tinygo/mpccore
//
// File is generated by gobind. Do not edit.

#ifndef __Mpccore_H__
#define __Mpccore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MpccoreResult;

@interface MpccoreResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull res;
@property (nonatomic) NSString* _Nonnull r1;
@property (nonatomic) NSString* _Nonnull r2;
@property (nonatomic) NSString* _Nonnull r3;
@end

FOUNDATION_EXPORT NSString* _Nonnull const MpccoreERR;
FOUNDATION_EXPORT NSString* _Nonnull const MpccoreEcdsa_Type;
FOUNDATION_EXPORT NSString* _Nonnull const MpccoreSUCC;

@interface Mpccore : NSObject
// skipped variable Ecdsa_Curve with unsupported type: *github.com/decred/dcrd/dcrec/secp256k1/v2.KoblitzCurve

@end

FOUNDATION_EXPORT NSString* _Nonnull MpccoreKeyGen(NSString* _Nullable signType);

FOUNDATION_EXPORT NSString* _Nonnull MpccoreReshare(NSString* _Nullable signType, NSString* _Nullable pubkey, NSString* _Nullable chainCode, NSString* _Nullable shareI1, NSString* _Nullable shareI2, long keyid);

FOUNDATION_EXPORT NSString* _Nonnull MpccoreSignMessage(NSString* _Nullable p1ShareI, NSString* _Nullable paiStr, long fromId, long toId);

#endif
